# this enables a /dev/zram0
# size equals available memory or 8gb, whichever is less
# to disable, comment out the section below or remove this file.
#
[zram0]
zram-size = min(ram, 8192)
compression-algorithm = zstd
