#!/bin/bash
#
# mask zfs auto-import/auto-mount for this boot only, this prevents a stall/hang
# white booting, stopping the installer from interacting with zfs partitions on target
# (this file will be automatically removed upon first boot)
#
set -euo pipefail

root_fstype=$(findmnt -no FSTYPE / || echo unknown)

if [ "${root_fstype}" = "overlay" ]; then
    systemctl mask --runtime \
        zfs.target \
        zfs-import.target \
        zfs-import-scan.service \
        zfs-import-cache.service \
        zfs-load-module.service \
        zfs-volumes.target \
        zfs-volume-wait.service \
        zfs-mount.service \
        zfs-share.service \
        zfs-zed.service \
        || true
fi

exit 0
