# auto login for "liveuser" when booting into a live session
# (this file will be automatically removed upon first boot)
#
[daemon]
AutomaticLoginEnable=true
AutomaticLogin=liveuser

[security]

[xdmcp]

[chooser]

[debug]
